name: observable_locator
description: A service locator that uses MobX for reactive dependencies
version: 0.3.0

homepage: https://github.com/brianrobles204/observable_locator

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  meta: ^1.3.0
  mobx: ^2.0.4

dev_dependencies:
  pedantic: ^1.10.0
  rxdart: ^0.27.1
  test: ^1.16.0
